# Uke 37: Samlinger
<div>
<img src="https://files.realpython.com/media/Lists-and-Tuples_Watermarked.a1232313125d.jpg" width="500"/>
</div>

Denne uken skal vi lære om:
- lister
- tupler
- dictionaries
- arrayer

Ønsker du å se flere eksempeler / forklaringer, kan jeg anbefale å bruke denne nettsiden: https://www.w3schools.com/PYTHON/


**Onsdag 28.08.2024**

https://www.w3schools.com/python/python_lists.asp

https://www.w3schools.com/python/numpy/numpy_creating_arrays.asp

https://www.w3schools.com/PYTHON/python_dictionaries.asp

Lists are used to store multiple items in a single variable.

Lists are one of 4 built-in data types in Python used to store collections of data, the other 3 are Tuple, Set, and Dictionary, all with different qualities and usage.

Lists are created using square brackets:

List items are ordered, changeable, and allow duplicate values.

List items are indexed, the first item has index [0], the second item has index [1] etc.

When we say that lists are ordered, it means that the items have a defined order, and that order will not change.

If you add new items to a list, the new items will be placed at the end of the list.

The list is changeable, meaning that we can change, add, and remove items in a list after it has been created.

Since lists are indexed, lists can have items with the same value:

List items can be of any data type:

A list can contain different data types:


> List is a collection which is ordered and changeable. Allows duplicate members.
Tuple is a collection which is ordered and unchangeable. Allows duplicate members.
Set is a collection which is unordered, unchangeable*, and unindexed. No duplicate members.
Dictionary is a collection which is ordered** and changeable. No duplicate members.




In [ ]:
thislist = ["apple", "banana", "cherry", "blåbær", "mango"]
print(thislist)

print(len(thislist))    #Lengde på en liste / antallet gjenstander den inneholder
print(type(thislist))

#Hente ut gjenstander i en liste
print(thislist[1])
print(thislist[-1])
print(thislist[2:5])    #Område
print(thislist[:4])     #Område
print(thislist[2:])     #Område

print(thislist[-1:-4])  #Hva skjer her? Diskuter

if "apple" in thislist:
  print("Yes, 'apple' is in the fruits list")

#forandre på verdier i en liste
thislist[1] = "blackcurrant"
thislist[1:3] = ["blackcurrant", "watermelon"]
thislist[1:2] = ["blackcurrant", "watermelon"]
thislist[1:3] = ["watermelon"]

#liste-metoder
thislist.insert(2, "watermelon")
thislist.append('appelsin')
thislist.extend([1,2,3])    #legger til iterable objekt
thislist.remove("banana")
thislist.pop(1)
del thislist[0]
thislist.clear()

In [ ]:
thislist = ["apple", "banana", "cherry"]
for x in thislist:
  print(x)

for i in range(len(thislist)):
  print(thislist[i])

i = 0
while i < len(thislist):
  print(thislist[i])
  i = i + 1

[print(x) for x in thislist]

In [ ]:
lst = [x + 1 for x in range(10) if x%2]

print(lst)

In [ ]:
s = 'streng tekst'

type(s)  #gir objecttype
lst = s.split()   #deler en streng ved best tegn. Default er ' ' (mellomrom).

print(lst)

lst.append('eksempel')  #Legger til eksempel i listen. Havner på slutten.

print(lst)

print(lst[0])
print(lst[1])

In [ ]:
thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}

x = thisdict["model"]
x = thisdict.get('model')
y = thisdict.keys()
thisdict["brand"] = 'Toyota'

dict2 = thisdict.copy()

thisdict.pop('model')

print(x)
print(y)
print(thisdict)

In [123]:
# Onsdag 28. august 2024 time

lst = ['Martin','Alvin']

print(len(lst))

print(lst[0])
print(lst[1])

lst.append('Anders')
lst.sort()

print(lst)

#kommandoer for å fjerne elementer fra liste
#lst.remove('Martin') #fjerner spesifikt element
lst.pop(1) #fjerner siste(default) eller spesifikt element iht. indeks

print(lst)




2
Martin
Alvin
['Alvin', 'Anders', 'Martin']
['Alvin', 'Martin']


In [126]:
t = 'TeXt'

print(t.upper())
print(t.lower())

TEXT


In [144]:
#tupple = ('navn', 2, True)

tupple1 = (1 , 2, 3, 1, 1, 2)
tupple2 = (9, 8, 7)

#print(tupple1)
#print(tupple1+tupple2)

print(tupple1.index(1))



0


In [146]:
tupple = ('navn', 2, True)


print(list(tupple))

['navn', 2, True]


In [2]:
spill = {'navn':'Warcraft 3',
         'utgiver':'Blizzard',
         'år':2002}

print(spill)

#print(spill)

print(spill.keys()) #lager oversikt over nøklene i dictionary

print(spill.values())

spill.pop('utgiver')

spill.update({'genre':'Real Time Strategy'})

print(spill)

{'navn': 'Warcraft 3', 'utgiver': 'Blizzard', 'år': 2002}
dict_keys(['navn', 'utgiver', 'år'])
dict_values(['Warcraft 3', 'Blizzard', 2002])
{'navn': 'Warcraft 3', 'år': 2002, 'genre': 'Real Time Strategy'}


In [174]:
import numpy as np

# from numpy import array

lst1 = [1,2,3]
lst2 = [9,8,7]

A = np.array(lst1)
B = np.array(lst2)

print(A)
print(B)

C = A + B

print(C)

[1 2 3]
[9 8 7]
[10 10 10]
